img = document.querySelector(".img");
imgmain = document.querySelector("img");
menublock = document.querySelector(".menu-block");
menu = document.querySelector(".menu")
select = document.querySelector("select")
options = document.querySelector(".options")
btn = document.querySelector(".btn")
atag = document.querySelector("a")
input = document.querySelector("input")
line = document.querySelector(".line-element")
maintext = document.querySelector(".main-text")
h3tag = document.querySelector("h3")
ptag = document.querySelector("p")
cards = document.querySelector(".cards");
card = document.querySelectorAll(".card");
cardh3 = document.querySelectorAll(".card-h3");
cardp = document.querySelectorAll(".card-p");
cardi = document.querySelectorAll("i");
img.style.width = "100%";
img.style.height = "80px";
img.style.position = "relative";
imgmain.style.width = "100%";
imgmain.style.height = "100%";
imgmain.style.objectFit = "cover";
menublock.style.width = "100%";
menu.style.display = "flex";
menu.style.justifyContent = "space-around";
menu.style.padding = "25px";
menu.style.width = "70%";
menu.style.background = "white";
menu.style.margin = "0 auto";
menu.style.bottom = "40px";
menu.style.position = "relative";  
options.style.display = "flex";
select.style.padding = "10px 30px 5px";
btn.style.padding = "10px";
btn.style.border = "2px solid white";
btn.style.boxShadow = "7px 5px 5px #ffbf43";
btn.style.background = "#ffbf43"
atag.style.textDecoration = "none";
atag.style.color = "white";
atag.style.fontWeight = "bold";
input.style.marginLeft = "10px";
input.style.width = "198px";
line.style.width = "2px";
line.style.height = "39px";
line.style.background = "gray";
maintext.style.width = "40%";
maintext.style.margin = "0 auto";
h3tag.style.fontSize = "30px"
h3tag.style.textAlign = "center";
ptag.style.fontSize = "15px";
ptag.style.textAlign = "center";
ptag.style.color = "gray";
ptag.style.paddingTop = "10px";
cards.style.width = "80%";
cards.style.margin = "0 auto";
cards.style.display = "flex";
for(var i=0;i<card.length;i++){
    card[i].style.width = "25%";
    card[i].style.paddingTop = "10%";
    card[i].style.textAlign = "center";
}
for(var i=0;i<cardi.length;i++){
    cardi[i].style.width = "45px";
    cardi[i].style.height = "45px";
    cardi[i].style.borderRadius = "100%";
    cardi[i].style.textAlign = "center";
    cardi[i].style.lineHeight = "45px";
    cardi[i].style.fontSize = "20px"
    cardi[i].style.color = "white";
    cardi[0].style.background = "#f1574d";
    cardi[1].style.background = "#96ca4b";
    cardi[2].style.background = "#63abdb";
    cardi[3].style.background = "#5ce2d7";

}
for(var i=0;i<cardh3.length;i++){
    cardh3[i].style.fontSize = "20px";
    cardh3[i].style.fontWeight = "bold";
    cardh3[i].style.paddingTop = "10%"
}
for(var i =0;i<cardp.length;i++){
    cardp[i].style.fontSize = "17px";
    cardp[i].style.color = "gray";
    cardp[i].style.paddingTop = "10%"
}

